name: test
on:
  push:
    branches: ['**']
    tags-ignore: ['**']
jobs:
  lint:
    runs-on: ubuntu-latest    
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: setup node        
        uses: actions/setup-node@main        
        with:
          cache-dependency-path: '**/yarn.lock'
          node-version: 18
          cache: 'yarn'

      - name: ci        
        run: yarn install --immutable --immutable-cache --check-cache    

      - name: lint        
        run: yarn lint      

  tsc:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: setup node
        uses: actions/setup-node@main
        with:
          cache-dependency-path: '**/yarn.lock'
          node-version: 18
          cache: 'yarn'

      - name: ci        
        run: yarn install --immutable --immutable-cache --check-cache        

      - name: tsc        
        run: yarn tsc      
        
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: setup node
        uses: actions/setup-node@main
        with:
          cache-dependency-path: '**/yarn.lock'
          node-version: 18
          cache: 'yarn'

      - name: ci        
        run: yarn install --immutable --immutable-cache --check-cache    

      - name: build        
        run: yarn build
