name: test
on:
  push:
    branches: ['**']
    tags-ignore: ['**']
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: setup node        
        uses: actions/setup-node@main        
        with:
          cache-dependency-path: ${{ env.working-directory }}/yarn.lock
          node-version: 18
          cache: 'yarn'

      - name: lint
        working-directory: ${{ env.working-directory }}        
        run: yarn lint      

  tsc:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: setup node
        uses: actions/setup-node@main
        with:
          cache-dependency-path: ${{ env.working-directory }}/yarn.lock
          node-version: 18
          cache: 'yarn'

      - name: tsc
        working-directory: ${{ env.working-directory }}        
        run: yarn tsc      
        
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: setup node
        uses: actions/setup-node@main
        with:
          cache-dependency-path: ${{ env.working-directory }}/yarn.lock
          node-version: 18
          cache: 'yarn'

      - name: build
        working-directory: ${{ env.working-directory }}        
        run: yarn build
