name: test
on:
  push:
    branches: ['**']
    tags-ignore: ['**']
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: setup node
        uses: actions/setup-node@main
        with:
          node-version: 18
          cache: 'npm'

      - name: lint
        working-directory: client
        run: yarn lint      

  tsc:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: setup node
        uses: actions/setup-node@main
        with:
          node-version: 18
          cache: 'npm'

      - name: tsc
        working-directory: client
        run: yarn tsc      
        
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: setup node
        uses: actions/setup-node@main
        with:
          node-version: 18
          cache: 'npm'

      - name: build
        working-directory: client
        run: yarn build
